# Generated by Django 4.1.3 on 2023-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="admin", max_length=30, unique=True),
        ),
    ]
