# Generated by Django 4.1.3 on 2023-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0002_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
