# Generated by Django 4.1.3 on 2023-03-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0004_movie_person"),
    ]

    operations = [
        migrations.DeleteModel(name="Movie",),
    ]
