# Generated by Django 4.1.3 on 2023-04-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0008_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("comment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("movie_id", models.IntegerField()),
                ("content", models.TextField()),
            ],
        ),
    ]
