# Generated by Django 4.1.3 on 2023-04-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0009_comments"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
