# Generated by Django 4.1.3 on 2023-04-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0010_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie", name="name", field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name="movie", name="regions", field=models.CharField(max_length=100),
        ),
    ]
