# Generated by Django 4.1.3 on 2023-04-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0011_alter_movie_name_alter_movie_regions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name": "评论信息管理", "verbose_name_plural": "评论信息管理"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "电影信息管理", "verbose_name_plural": "电影信息管理"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "演员信息管理", "verbose_name_plural": "演员信息管理"},
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="评论ID"
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=models.TextField(verbose_name="评论内容"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="movie_id",
            field=models.IntegerField(verbose_name="电影ID"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.TextField(verbose_name="主演"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="alias",
            field=models.CharField(max_length=200, verbose_name="别名"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="cover",
            field=models.CharField(max_length=150, verbose_name="封面地址"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.CharField(max_length=150, verbose_name="导演"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.CharField(max_length=50, verbose_name="类型"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="languages",
            field=models.CharField(max_length=60, verbose_name="语言"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="mins",
            field=models.CharField(max_length=15, verbose_name="片长"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movie_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="电影ID"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=110, verbose_name="电影名"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="regions",
            field=models.CharField(max_length=100, verbose_name="制片国家/地区"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.CharField(max_length=4, verbose_name="上映年份"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(verbose_name="豆瓣评分"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="storyline",
            field=models.TextField(verbose_name="电影描述"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=50, verbose_name="演员姓名"),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="演员ID"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="sex",
            field=models.CharField(max_length=4, verbose_name="演员性别"),
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                ("movie_id", models.IntegerField(verbose_name="电影ID")),
                ("rating", models.IntegerField(verbose_name="评分等级")),
            ],
            options={
                "verbose_name": "评分信息管理",
                "verbose_name_plural": "评分信息管理",
                "unique_together": {("user_id", "movie_id")},
            },
        ),
    ]
