# Generated by Django 4.1.3 on 2023-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0012_alter_comments_options_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField(verbose_name="电影ID")),
                ("movie_name", models.CharField(max_length=110, verbose_name="电影名")),
                ("genres", models.CharField(max_length=4, verbose_name="类型")),
            ],
            options={"verbose_name": "类型信息管理", "verbose_name_plural": "类型信息管理",},
        ),
    ]
