# Generated by Django 4.1.3 on 2023-04-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0014_rename_genres_genres_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genres",
            name="genre",
            field=models.CharField(max_length=15, verbose_name="类型"),
        ),
    ]
