# Generated by Django 4.1.3 on 2023-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0015_alter_genres_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField(unique=True, verbose_name="电影ID")),
            ],
        ),
    ]
