# Generated by Django 4.1.3 on 2023-04-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0017_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languages",
            name="language",
            field=models.CharField(max_length=30, verbose_name="语种"),
        ),
    ]
