# Generated by Django 4.1.3 on 2023-04-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0018_alter_languages_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languages",
            name="language",
            field=models.CharField(max_length=50, verbose_name="语种"),
        ),
    ]
