# Generated by Django 4.1.3 on 2023-04-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("douban_app", "0019_alter_languages_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="mins",
            field=models.IntegerField(verbose_name="片长"),
        ),
    ]
